FROM node:20-alpine as build-stage

WORKDIR /app

# Copia os arquivos de configuração de dependências
COPY package*.json ./

# Instala as dependências do Node.js
RUN npm install

# Copia o restante do código da aplicação
COPY . .

# Constrói a aplicação para produção (cria a pasta 'dist')
RUN npm run build 

# Segundo estágio: Servir a aplicação com Nginx
FROM nginx:alpine as production-stage

# Copia a configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos estáticos da aplicação React para o diretório de serviço do Nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Expõe a porta que o Nginx vai escutar internamente no contêiner
EXPOSE 80

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]